---
- name: Upgrade packages to latest versions
  package:
    name: "*"
    state: latest
  become: yes

- name: Add SSH public key for user
  authorized_key:
    user: ubuntu
    key: "{{ lookup('file', public_key) }}"
    state: present
  become: yes
